"""Initial migration with all models: usuarios, empresas, practicantes, convocatorias, postulaciones, sugerencias, practicas, entregables, evaluaciones, certificados, reputaciones, notificaciones

Revision ID: 961515e32609
Revises: 
Create Date: 2026-07-20 17:36:54.113586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961515e32609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('activation_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_activation_token'), ['activation_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_password_reset_token'), ['password_reset_token'], unique=False)

    op.create_table('convocatorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('habilidades_requeridas', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite_postulacion', sa.DateTime(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('num_vacantes', sa.Integer(), nullable=True),
    sa.Column('duracion_meses', sa.Integer(), nullable=True),
    sa.Column('requiere_carnet', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convocatorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convocatorias_id'), ['id'], unique=False)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_id'), ['id'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('mensaje_html', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_id'), ['id'], unique=False)

    op.create_table('practicantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('habilidades', sa.JSON(), nullable=True),
    sa.Column('formacion_educativa', sa.JSON(), nullable=True),
    sa.Column('carnet_universitario', sa.String(length=20), nullable=True),
    sa.Column('dni', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('practicantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practicantes_id'), ['id'], unique=False)

    op.create_table('reputaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('evaluaciones_count', sa.Integer(), nullable=True),
    sa.Column('practicas_completadas', sa.Integer(), nullable=True),
    sa.Column('promedio_puntaje', sa.Float(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('reputaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reputaciones_id'), ['id'], unique=False)

    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=False),
    sa.Column('practicante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('mensaje_postulacion', sa.Text(), nullable=True),
    sa.Column('archivos_adjuntos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatorias.id'], ),
    sa.ForeignKeyConstraint(['practicante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postulaciones_id'), ['id'], unique=False)

    op.create_table('sugerencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=False),
    sa.Column('practicante_id', sa.Integer(), nullable=False),
    sa.Column('score_match', sa.Float(), nullable=False),
    sa.Column('habilidades_match', sa.JSON(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatorias.id'], ),
    sa.ForeignKeyConstraint(['practicante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sugerencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sugerencias_id'), ['id'], unique=False)

    op.create_table('practicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='estadopracticadb'), nullable=True),
    sa.Column('horario_trabajo', sa.Text(), nullable=True),
    sa.Column('supervisor_nombre', sa.String(length=100), nullable=True),
    sa.Column('supervisor_contacto', sa.String(length=100), nullable=True),
    sa.Column('acta_inicio_url', sa.String(length=255), nullable=True),
    sa.Column('acta_termino_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postulacion_id')
    )
    with op.batch_alter_table('practicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practicas_id'), ['id'], unique=False)

    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practica_id', sa.Integer(), nullable=False),
    sa.Column('codigo_unico', sa.String(length=16), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('url_verificacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practica_id')
    )
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_codigo_unico'), ['codigo_unico'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificados_id'), ['id'], unique=False)

    op.create_table('entregables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practica_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_limite_entrega', sa.DateTime(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENTREGADO', 'REVISADO', 'APROBADO', 'RECHAZADO', name='estadoentregabledb'), nullable=True),
    sa.Column('comentario_empresa', sa.Text(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entregables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entregables_id'), ['id'], unique=False)

    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criterios_evaluacion', sa.JSON(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_id'))

    op.drop_table('evaluaciones')
    with op.batch_alter_table('entregables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entregables_id'))

    op.drop_table('entregables')
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_id'))
        batch_op.drop_index(batch_op.f('ix_certificados_codigo_unico'))

    op.drop_table('certificados')
    with op.batch_alter_table('practicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practicas_id'))

    op.drop_table('practicas')
    with op.batch_alter_table('sugerencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sugerencias_id'))

    op.drop_table('sugerencias')
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postulaciones_id'))

    op.drop_table('postulaciones')
    with op.batch_alter_table('reputaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reputaciones_id'))

    op.drop_table('reputaciones')
    with op.batch_alter_table('practicantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practicantes_id'))

    op.drop_table('practicantes')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_id'))

    op.drop_table('notificaciones')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_id'))

    op.drop_table('empresas')
    with op.batch_alter_table('convocatorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convocatorias_id'))

    op.drop_table('convocatorias')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_activation_token'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
