"""add user activation and password reset tokens

Revision ID: 734d8ba24491
Revises: 54bdc5ed1969
Create Date: 2026-07-15 07:44:20.998833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734d8ba24491'
down_revision = '54bdc5ed1969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activation_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_activation_token'), ['activation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_password_reset_token'), ['password_reset_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_usuarios_activation_token'))
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('activation_token_expires_at')
        batch_op.drop_column('activation_token')

    # ### end Alembic commands ###
