"""create practicas, entregables, evaluaciones tables

Revision ID: e48551cea8e6
Revises: 734d8ba24491
Create Date: 2026-07-19 21:03:26.605568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48551cea8e6'
down_revision = '734d8ba24491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('practicante_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['practicante_id'], ['practicantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practica_id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practica_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluaciones')
    op.drop_table('entregables')
    op.drop_table('practicas')
    # ### end Alembic commands ###
